#!/usr/bin/env python3

import argparse
import json
import re
import glob
import hashlib
import os
import logging
from datetime import datetime

logging.basicConfig(format='%(levelname)s: %(asctime)s - %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        prog='run_processing2json.py',
        description="Creates json file for project tracking database from a Run generated by GenPipes Run Processing and Freezeman."
        )
    parser.add_argument(
        '-i',
        '--input',
        required=True,
        help="Folder of the Run to be converted. To be formatted like this /lb/robot/research/freezeman-processing/<sequencer>/<year>/<run_folder>."
        )
    parser.add_argument(
        '-o',
        '--output',
        default=None,
        help="Output json filename (Default: .json)."
        )
    parser.add_argument(
        '-n',
        '--nucleic_acid_type',
        choices=['DNA', 'RNA'],
        default='ALL',
        help="Nucleic Acid type, either DNA or RNA (Default: ALL)."
        )
    parser.add_argument(
        '-l',
        '--lane',
        nargs='+',
        default=["1", "2", "3", "4", "5", "6", "7", "8"],
        help="Only considers lane(s) provided for json creation."
        )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        '-s',
        '--sample',
        nargs='+',
        help="Only considers sample(s) provided for json creation."
        )
    group.add_argument(
        '-x',
        '--xsample',
        nargs='+',
        help="Ignores sample(s) provided for json creation."
        )
    return parser.parse_args()

def load_json_file(file_path):
    """Load a JSON file."""
    try:
        with open(file_path, mode="r") as file:
            return json.load(file)
    except FileNotFoundError:
        logger.error(f"JSON file not found: {file_path}")
    except json.JSONDecodeError:
        logger.error(f"Error decoding JSON file: {file_path}")
    return None

def jsonify_run_processing(input_run_folder, fms_json, lanes_json, output, lanes, samples, nucleic_acid_type):
    """
    Converts the Run Processing run validation file to a json file for project tracking database.
    Args:
        input_run_folder (str): Path to the Run Processing csv file.
        fms_json (json): JSON file from Freezeman.
        output (str): Path to the output json file.
        lanes (list): List of lanes to consider.
        samples (list): List of samples to consider.
        nucleic_acid_type (str): Nucleic Acid type to consider.
    """
    readset_dict = {}
    sample_dict = {}
    json_output = {
            "operation_platform": "abacus",
            "project_ext_id": None,
            "project_ext_src": None,
            "project_name": "NRGI_CPHI",
            "run_ext_id": fms_json["run_obj_id"],
            "run_ext_src": "FREEZEMAN",
            "run_name": input_run_folder.split("/")[-1],
            "run_instrument": "novaseqx",
            "run_date": f"{datetime.strptime(fms_json['run_start_date'], '%Y-%m-%d')}",
            "run_mean_coverage": None,
            "specimen": []
            }

    for _, lane_json in lanes_json.items():
        # calculate average coverage for lane
        sample_number = 0
        lane_coverage = 0
        for run_v in lane_json["run_validation"]:
            sample_number += 1
            lane_coverage += run_v.get("alignment", {}).get("mean_coverage")
        lane_mean_coverage = float(lane_coverage / sample_number)
        json_output["run_mean_coverage"] = lane_mean_coverage
        for readset_key, readset in lane_json["readsets"].items():
            sample_name = readset["sample_name"]
            if sample_name.startswith("NRGI") and lane_json['lane'] in lanes and sample_name in samples:
                specimen = readset["sample_name"]
                # Check if the specimen is already in json_output["specimen"]
                specimen_names = [spec["specimen_name"] for spec in json_output["specimen"]]
                if specimen in specimen_names:
                    # Specimen is present, find its position
                    position = specimen_names.index(specimen)
                    specimen_json = json_output["specimen"][position]
                else:
                    # Specimen is not present, add it to json_output["specimen"]
                    specimen_json = {
                        "specimen_ext_id": None,
                        "specimen_ext_src": None,
                        "specimen_name": specimen,
                        "specimen_readset": readset,
                        "specimen_cohort": None,
                        "specimen_institution": None,
                        "sample": []
                        }
                    json_output["specimen"].append(specimen_json)

                # Check if the sample is already in specimen_json["sample"]
                sample_names = [spec["sample_name"] for spec in specimen_json["sample"]]
                if sample_name in sample_names:
                    # sample is present, find its position
                    position = sample_names.index(sample_name)
                    sample_json = specimen_json["sample"][position]
                else:
                    # sample is not present, add it to specimen_json["sample"]
                    sample_json = {
                        "sample_ext_id": int(readset["derived_sample_obj_id"]),
                        "sample_ext_src": "FREEZEMAN",
                        "sample_name": sample_name,
                        "sample_tumour": False,
                        "readset": []
                        }
                    specimen_json["sample"].append(sample_json)

                cram = readset["bam"]["final_path"]
                crai = readset["bai"]["final_path"]
                dragen_tar = os.path.join(os.path.dirname(os.path.dirname(cram)), f"{sample_name}_{readset["derived_sample_obj_id"]}.dragen_outputs.tar.gz")
                file_json = [
                    {
                        "location_uri": f"abacus://{cram}",
                        "file_name": f"{os.path.basename(cram)}",
                        "file_md5sum": compute_md5(cram),
                        "file_deliverable": True
                        },
                    {
                        "location_uri": f"abacus://{crai}",
                        "file_name": f"{os.path.basename(crai)}",
                        "file_md5sum": compute_md5(crai),
                        "file_deliverable": True
                        },
                    {
                        "location_uri": f"abacus://{dragen_tar}",
                        "file_name": f"{os.path.basename(dragen_tar)}",
                        "file_md5sum": compute_md5(dragen_tar),
                        "file_deliverable": True
                    }
                    ]
                for job in next(step["jobs"] for step in lane_json["steps"] if step["step_name"] == "align"):
                    if f"dragen_processing.{readset_key}" in job.get("job_name"):
                        job_name = job.get("job_name")
                        cmd_line = job.get("command")
                        ref_name, ref_version, ref_alias = get_reference(cmd_line)

                        operation_json = [
                            {
                                "operation_name": job_name,
                                "operation_cmd_line": cmd_line,
                                "reference_name": ref_name,
                                "reference_alias": ref_alias,
                                "reference_version": ref_version
                            }
                        ]
                for run_v in lane_json["run_validation"]:
                    if run_v.get("sample") == readset_key:
                        raw_reads_count = run_v.get("qc", {}).get("nb_reads")
                        raw_reads_count_flag = get_flag(raw_reads_count)
                        raw_reads_count, raw_reads_count_flag = check_na(raw_reads_count, raw_reads_count_flag)
                        if raw_reads_count == 0:
                            raw_reads_count_flag = "FAILED"
                        if readset["library_type"] == "RNASeq":
                            raw_reads_count_flag = rna_raw_reads_count_check(sample_name, raw_reads_count)

                        raw_duplication_rate = run_v.get("qc", {}).get("duplicate_rate")
                        raw_duplication_rate_flag = get_flag(raw_duplication_rate)
                        if readset["library_type"] != "RNASeq":
                            raw_duplication_rate_flag = dna_raw_duplication_rate_check(sample_name, raw_duplication_rate)
                        raw_duplication_rate, raw_duplication_rate_flag = check_na(raw_duplication_rate, raw_duplication_rate_flag)

                        raw_median_insert_size = run_v.get("alignment", {}).get("median_aligned_insert_size")
                        raw_median_insert_size_flag = median_insert_size_check(sample_name, raw_median_insert_size) if raw_median_insert_size else "MISSING"
                        raw_median_insert_size, raw_median_insert_size_flag = check_na(raw_median_insert_size, raw_median_insert_size_flag)

                        raw_mean_insert_size = run_v.get("alignment", {}).get("average_aligned_insert_size")
                        raw_mean_insert_size_flag = get_flag(raw_mean_insert_size)
                        raw_mean_insert_size, raw_mean_insert_size_flag = check_na(raw_mean_insert_size, raw_mean_insert_size_flag)

                        raw_mean_coverage = run_v.get("alignment", {}).get("mean_coverage")
                        raw_mean_coverage_flag = get_flag(raw_mean_coverage)
                        raw_mean_coverage, raw_mean_coverage_flag = check_na(raw_mean_coverage, raw_mean_coverage_flag)
                        if raw_mean_coverage_flag == "PASS" and readset["library_type"] != "RNASeq":
                            raw_mean_coverage_flag = dna_raw_mean_coverage_check(sample_name, raw_mean_coverage, lane_mean_coverage)     
                        metric_json = [
                            {
                                "metric_name": "raw_reads_count",
                                "metric_value": raw_reads_count,
                                "metric_flag": raw_reads_count_flag,
                                "metric_deliverable": True
                                },
                            {
                                "metric_name": "raw_duplication_rate",
                                "metric_value": raw_duplication_rate,
                                "metric_flag": raw_duplication_rate_flag
                                },
                            {
                                "metric_name": "raw_median_insert_size",
                                "metric_value": raw_median_insert_size,
                                "metric_flag": raw_median_insert_size_flag
                                },
                            {
                                "metric_name": "raw_mean_insert_size",
                                "metric_value": raw_mean_insert_size,
                                "metric_flag": raw_mean_insert_size_flag
                                },
                            {
                                "metric_name": "raw_mean_coverage",
                                "metric_value": raw_mean_coverage,
                                "metric_flag": raw_mean_coverage_flag
                                }
                            ]

                readset_name = f"{sample_name}_{readset["derived_sample_obj_id"]}_{lane_json['run_obj_id']}_L00{lane_json['lane']}"
                readset_dict[readset_name] = (specimen, sample_name)
                # Check if the readset is already in sample_json["readset"]
                readset_names = [spec["readset_name"] for spec in sample_json["readset"]]
                if readset_name in readset_names:
                    print(f"Duplicate readset: {readset_name}")
                else:
                    # readset is not present, add it to specimen_json["readset"]
                    for fms_s in fms_json["samples"]:
                        if fms_s.get("sample_name") == sample_name:
                            library_kit = fms_s["library_kit"]
                    readset_json = {
                        "experiment_sequencing_technology": None,
                        "experiment_type": f"{readset['library_type']}",
                        "experiment_nucleic_acid_type": "RNA" if readset["library_type"] == "RNASeq" else "DNA",
                        "experiment_library_kit": library_kit,
                        "experiment_kit_expiration_date": None,
                        "readset_name": readset_name,
                        "readset_lane": f"{lane_json['lane']}",
                        "readset_adapter1": f"{readset['barcodes'][0]['ADAPTERi7']}",
                        "readset_adapter2": f"{readset['barcodes'][0]['ADAPTERi5']}",
                        "readset_sequencing_type": f"{lane_json['sequencing_method']}",
                        "readset_quality_offset": "33",
                        "file": file_json,
                        "metric": metric_json,
                        "operation": operation_json
                        }
                    sample_json["readset"].append(readset_json)

    specimens_to_remove = []
    for specimen in json_output.get("specimen", []):
        samples_to_remove = []
        for sample in specimen.get("sample", []):
            readsets_to_remove = []
            for readset in sample.get("readset", []):
                if readset.get("experiment_nucleic_acid_type") != nucleic_acid_type and nucleic_acid_type != 'ALL':
                    readsets_to_remove.append(readset)
            for readset in readsets_to_remove:
                sample["readset"].remove(readset)
            if not sample["readset"]:
                samples_to_remove.append(sample)
        for sample in samples_to_remove:
            specimen["sample"].remove(sample)
        if not specimen["sample"]:
            specimens_to_remove.append(specimen)
    for specimen in specimens_to_remove:
        json_output["specimen"].remove(specimen)

    with open(output, 'w', encoding='utf-8') as file:
        json.dump(json_output, file, ensure_ascii=False, indent=4)

    return readset_dict, sample_dict

def check_na(value, flag):
    """ Check if value is 'NA' and set flag to 'NOT_APPLICABLE' """
    if value == "N/A":
        value = None
        flag = "NOT_APPLICABLE"
    return value, flag

def get_flag(value, default="PASS", missing="MISSING"):
    """ Get flag for metric """
    return default if value is not None else missing

def dna_raw_mean_coverage_check(sample, value, lane_mean):
    """ Mean Coverage DNA metric check """
    if not value:
        ret = "MISSING"
        logger.warning(f"Missing 'mean_coverage' value for {sample} from json.")
    elif float(lane_mean)<30:
        ret = "FAILED"
    else:
        ret = "PASS"
    return ret

def rna_raw_reads_count_check(sample, value):
    """ Clusters RNA metric check """
    if not value:
        ret = "MISSING"
        logger.warning(f"Missing 'nb_reads' value for {sample} from json.")
    if int(value)<80000000:
        ret = "FAILED"
    elif int(value)<100000000:
        ret = "WARNING"
    else:
        ret = "PASS"
    return ret

def dna_raw_duplication_rate_check(sample, value):
    """ Dup. Rate DNA metric check """
    if not value:
        ret = "MISSING"
        logger.warning(f"Missing 'duplication_rate' value for {sample} from json.")
    elif float(value)>0.5:
        ret = "FAILED"
    elif float(value)>0.2:
        ret = "WARNING"
    else:
        ret = "PASS"
    return ret

def median_insert_size_check(sample, value):
    """ Mapped Insert Size (median) metric check """
    if not value:
        ret = "MISSING"
        logger.warning(f"Missing 'median_aligned_insert_size' value for {sample} from json.")
    if float(value)<300:
        ret = "WARNING"
    elif float(value)<150:
        ret = "FAILED"
    else:
        ret = "PASS"
    return ret

def get_reference(command):
    """ Parse reference used from dragen command """
    ref_dir = re.search(r"--ref-dir \S*", command)[0].split(" ")[1]
    ref_name = os.path.basename(ref_dir).split("-")[0]
    ref_version = re.sub(f"{ref_name}-", '', os.path.basename(ref_dir))
    annotation_assembly = re.search(r"--variant-annotation-assembly \S*", command)[0].split(" ")[1]

    return ref_name, ref_version, annotation_assembly

def compute_md5(file_path, chunk_size=8 * 1024 * 1024):  # 8MB chunks
    """Compute or retrieve MD5 checksum of a file using EAFP style."""
    md5_file_path = f"{file_path}.md5sum"

    try:
        with open(md5_file_path, 'r') as f:
            line = f.readline()
            return line.split()[0]
    except (FileNotFoundError, IOError):
        pass  # Proceed to compute MD5 if .md5 file doesn't exist or can't be read

    # Compute MD5
    md5 = hashlib.md5()
    with open(file_path, 'rb') as f:
        while chunk := f.read(chunk_size):
            md5.update(chunk)
    return md5.hexdigest()

def main():
    """ Main """
    args = parse_arguments()

    output = args.output or f"{os.path.basename(args.input)}.json"
    lanes = args.lane

    json_candidates = glob.glob(os.path.join(args.input, "*.json"))
    json_main = [p for p in json_candidates if "dragen" not in os.path.basename(p)]
    if not json_main:
        raise FileNotFoundError(f"No main .json file (without lane suffix) found in folder {args.input}.")
    fms_json = load_json_file(json_main[0])

    lanes_json_files = glob.glob(os.path.join(args.input, "report", "*.run_validation_report.json"))
    lanes_json = {os.path.basename(file): load_json_file(file) for file in lanes_json_files}

    if args.sample:
        samples = list(args.sample)
    elif args.xsample:
        all_samples = [sample["sample_name"] for sample in fms_json["samples"]]
        samples = list(set(all_samples).difference(set(args.xsample)))
    else:
        samples = [sample["sample_name"] for sample in fms_json["samples"]]

    jsonify_run_processing(args.input, fms_json, lanes_json, output, lanes, samples, args.nucleic_acid_type)

if __name__ == '__main__':
    main()
